"""empty message

Revision ID: 3fd48c0f327d
Revises: 8b1964a3afd6
Create Date: 2022-08-12 01:00:35.974858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd48c0f327d'
down_revision = '8b1964a3afd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=250), nullable=True))
    op.add_column('Artist', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('talent_search', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website_link', sa.String(length=200), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('talent_search', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'description')
    op.drop_column('Venue', 'talent_search')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'talent_search')
    op.drop_column('Artist', 'description')
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
